# Generated by Django 4.1.7 on 2023-02-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EphemeralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'New Ticket'), ('N', 'New Notification')], max_length=1)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('safaricom_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('paybill_no', models.CharField(max_length=15)),
                ('airtel_no', models.CharField(max_length=15)),
                ('issue', models.CharField(choices=[('EA', 'Excess Airtime'), ('BWN', 'Buying To Wrong Number'), ('NC', 'Not Credited'), ('O', 'Others')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_info', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency', models.CharField(choices=[('D', 'Default'), ('U', 'Urgent'), ('M', 'Emergency')], default='D', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('C', 'Closed'), ('O', 'Opened')], default='P', max_length=1)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('ephemeraluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TicketingApp.ephemeraluser')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketingApp.company')),
                ('notifications', models.ManyToManyField(blank=True, to='TicketingApp.notification')),
                ('tickets', models.ManyToManyField(blank=True, to='TicketingApp.ticket')),
            ],
            options={
                'ordering': ['company'],
            },
            bases=('TicketingApp.ephemeraluser', models.Model),
        ),
    ]
