# Generated by Django 4.1.7 on 2023-02-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notifications',
        ),
    ]
