# Generated by Django 4.1.7 on 2023-02-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0002_remove_customuser_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
