# Generated by Django 4.1.7 on 2023-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0003_notification_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
