# Generated by Django 4.1.7 on 2023-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketingApp', '0004_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
